packages:
  # all packages in direct subdirs of apps/
  - 'apps/*'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'libs/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
